# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # package
      - run: mvn clean package -Dbuild=$CIRCLE_BUILD_NUM

      - store_artifacts:
          path: deploy

  workflows:
    version: 2
      jobs: 
        - build
